[package]
name = "ferris"
version = "0.1.0"
edition = "2021"

[dependencies]
structopt = "0.3"
walkdir = "2.3"
rayon = "1.5"
sha2 = "0.9"
log = "0.4"
env_logger = "0.8"
threadpool = "1.8"
num_cpus = "1.13"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
libc = "0.2.158"

